#!/usr/bin/env bash

# Destroy (force stop) and completely remove a VM.
# Probably kind of dangerous to script this, but
# can be useful for testing.

virsh destroy "$1"
virsh undefine "$1" \
    --remove-all-storage \
    --managed-save \
    --snapshots-metadata
