#!/usr/bin/env bash

CONFIG=config

if [ -f "$CONFIG" ]; then
    . "$CONFIG"
else
    echo "No config file found."
    exit 1
fi


INSTANCE_ID=v01

if [ -z "${1}" ]; then 
    USER_DATA=user-data
else
    USER_DATA="$1"
    cp $USER_DATA user-data
fi

if [ -z "${POOL_NAME}" ]; then 
    POOL_NAME=default
fi
if [ -z "${POOL_PATH}" ]; then
    POOL_PATH=$( virsh pool-dumpxml $POOL_NAME | xmllint --xpath '//target/path/text()' - | head -n 1 )
fi
if [ -z "${RAM}" ]; then 
    RAM=1024
fi
if [ -z "${VCPUS}" ]; then 
    VCPUS=1
fi

HOSTNAME=$( grep -iEo '\s*hostname.*$' "$USER_DATA" | grep -iEo '\s\w+$' | grep -iEo '\w+' | head -n 1 )

cat <<EOF > meta-data
instance-id: ${HOSTNAME}-${INSTANCE_ID}
local-hostname: $HOSTNAME
hostname: $HOSTNAME
EOF

genisoimage -output "${HOSTNAME}-config.iso" -volid cidata -joliet -rock user-data meta-data

sudo cp ${HOSTNAME}-config.iso "$POOL_PATH"
virsh pool-refresh "$POOL_NAME"
rm ${HOSTNAME}-config.iso
rm meta-data

BASE_SIZE=$( qemu-img info "$BASE_IMG" | grep -Eo '[0-9]+ bytes' | grep -Eo '[0-9]+' )

virsh vol-create-as \
    --pool $POOL_NAME \
    --name ${HOSTNAME}.img \
    --capacity $BASE_SIZE \
    --format qcow2 \
    --prealloc-metadata

virsh vol-upload \
    --vol ${HOSTNAME}.img \
    --pool $POOL_NAME \
    --file "$BASE_IMG"

if [ -n "${SIZE}" ]; then
    virsh vol-resize \
        --vol ${HOSTNAME}.img \
        --pool $POOL_NAME \
        --capacity "$SIZE"
fi

echo Installing:
echo "Hostname:  $HOSTNAME"
echo "Pool Name: $POOL_NAME"
echo "Pool Path: $POOL_PATH"

virt-install \
    --name $HOSTNAME \
    --ram $RAM \
    --vcpus $VCPUS \
    --cpu host \
    --autostart \
    --memballoon virtio \
    --network bridge=br0,model=virtio \
    --boot hd \
    --disk vol=${POOL_NAME}/${HOSTNAME}.img,format=qcow2,bus=virtio,cache=writeback \
    --disk vol=${POOL_NAME}/${HOSTNAME}-config.iso,bus=virtio
